name: Run Crypto Automation Script

on:
  schedule:
    - cron: '0 8 * * *'  # Exécute le script tous les jours à 08:00 UTC
  workflow_dispatch:    # Permet d'exécuter manuellement le workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Spécifiez la version de Python utilisée

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
          LUNARCRUSH_API_KEY: ${{ secrets.LUNARCRUSH_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          BITQUERY_API_KEY: ${{ secrets.BITQUERY_API_KEY }}
          CRYPTO_NEWS_RSS_URL: ${{ secrets.CRYPTO_NEWS_RSS_URL }}
          LOG_LEVEL: 'INFO'
        run: |
          source venv/bin/activate
          python script_crypto_automation.py

      - name: Send Webhook to Make.com
        if: success()
        uses: dawidd6/action-send-webhook@v2
        with:
          url: ${{ secrets.MAKE_WEBHOOK_URL }}
          method: 'POST'
          headers: 'Content-Type: application/json'
          payload: |
            {
              "message": "Script d'automatisation crypto exécuté avec succès.",
              "timestamp": "${{ github.event.schedule ? github.event.schedule.cron : 'manual' }}"
            }
